# If you add a page, you must add it to the index here
pages:
- INTRODUCTION:
  - About: 'index.md'
  - Architectural Overview: 'coral_ecosystem.md'
- DEVELOPER USER GUIDE:
  - Installing Coral Ecosystem: 'quickstart/install.md'
  - Cay:
    - Overview: 'cay/index.md'
    - Installation: 'cay/install.md'
  - Elkhorn:
    - Overview: 'elkhorn/index.md'
    - Installation: 'elkhorn/install.md'
  - Pillar:
    - Introduction: 'pillar/index.md'
    - Installation: 'pillar/install.md'
    - API: 'pillar/api.md'
  - Sponge:
    - Introduction: 'sponge/index.md'
    - Installation: 'sponge/install.md'
    - Development:
      - Logging: 'sponge/logging.md'
      - Included packages: 'sponge/included_packages.md'
  - Xenia:
    - Overview: 'xenia/index.md'
    - Installation: 'xenia/install.md'
  - Xenia Driver:
    - Overview: 'xenia/xenia-driver-js.md'
    - Installation: 'xenia/xenia-driver-js-install.md'
- CONTRIBUTE:
  - Introduction: 'contributions/index.md'
  - DEVELOPMENT:
    - Development workflow: 'contributions/development/working_with_github.md'
    - Writing Code: 'contributions/development/writing_code.md'
    - Conventions: 'contributions/development/code_style.md'
  - DOCUMENTATION:
    - Writing documentation: 'contributions/development/code_style.md'
  - Reporting Bugs: 'contributions/reporting_bugs.md'
  - Requesting Features: 'contributions/requesting_features.md'
  - Supporting the community: 'contributions/supporting_the_community.md'
  - Contributor License Agreements: 'contributions/contributor_license_agreement.md'
- FAQ: 'faq.md'


# Do not edit in PRs below here
site_name: The Coral Project Documentation

markdown_extensions:
  - admonition
  - fenced_code
  - sane_lists
  - smarty

extra_css:
  - css/code_fixer.css

theme: readthedocs
