# If you add a page, you must add it to the index here
pages:
- Home: 'index.md'
- Developer Guide:
  - Introduction: 'developer/index.md'
  - Architectural overview: 'developer/coral_ecosystem.md'
  - Installing Coral Ecosystem: 'quickstart/install.md'
  - Developer tools setup: 'developer/developer_setup.md'
  - Cay:
    - Introduction: 'cay/index.md'
    - Installation: 'cay/install.md'
  - Elkhorn:
    - Introduction: 'elkhorn/index.md'
    - Installation: 'elkhorn/install.md'
  - Pillar:
    - Introduction: 'pillar/index.md'
    - Installation: 'pillar/install.md'
    - API: 'pillar/api.md'
  - Sponge:
    - Introduction: 'sponge/index.md'
    - Installation: 'sponge/install.md'
    - Included packages: 'sponge/included_packages.md'
    - Strategy files: 'sponge/strategy.md'
    - Logging: 'sponge/logging.md'
  - Xenia:
    - Introduction: 'xenia/index.md'
    - Installation: 'xenia/install.md'
    - API and query management: 'xenia/api.md'
    - Testing: 'xenia/tests.md'
  - Xenia Driver:
    - Introduction: 'xenia/xenia-driver-js.md'
    - Installation: 'xenia/xenia-driver-js-install.md'
    - API: 'xenia/xenia-driver-js-api.md'
- User Guide:
  - Introduction: 'user/index.md'
  - Trust:
    - Overview: 'user/trust.md'
    - Tutorials: 'user/trust_tutorials.md'
  - Ask:
    - Overview: 'user/ask.md'
    - Tutorials: 'user/ask_tutorials.md'
  - Talk:
    - Overview: 'user/talk.md'
    - Tutorials: 'user/talk_tutorials.md'
- Contribute:
  - Introduction: 'contribute/index.md'
  - Writing documentation: 'contribute/documentation/writing_documentation.md'
  - Documentation style guide: 'contribute/documentation/style_guide.md'
  - Reporting bugs and requesting features: 'contribute/reporting_bugs.md'
  - Writing code: 'contribute/development/writing_code.md'
  - Development workflow: 'contribute/development/working_with_github.md'
  - Coding style guide: 'contribute/development/style_guide.md'
  - Supporting the community: 'contribute/supporting_the_community.md'
  - Contributor License Agreement: 'contribute/contributor_license_agreement.md'
  - Coral naming: 'contribute/coral_naming.md'
- FAQ: 'faq.md'


# Do not edit in PRs below here
site_name: Coral Project Docs

markdown_extensions:
  - admonition
  - fenced_code
  - sane_lists
  - smarty

theme: united

docs_dir: 'docs_dir'
