# If you add a page, you must add it to the index here
pages:
- Home: 'index.md'
- Products: products.md
- Developer Guide:
  - Introduction: 'developer/index.md'
  - Architectural overview: 'developer/architectural_overview.md'
  - Installing Coral Ecosystem: 'quickstart/install.md'
  - Developer tools setup: 'developer/developer_setup.md'
  - Cay: 'cay/index.md'
  - Elkhorn: 'elkhorn/index.md'
  - Pillar: 'pillar/index.md'
  - Sponge: 'sponge/index.md'
  - Xenia: 'xenia/index.md'
  - Xenia Driver: 'xenia/xenia-driver-js.md'
- User Guide:
  - Introduction: 'user/index.md'
  - Trust: 'user/trust.md'
  - Ask: 'user/ask.md'
  - Talk: 'user/talk.md'
- Contribute:
  - Introduction: 'contribute/index.md'
  - Writing documentation: 'contribute/writing_documentation.md'
  - Documentation style guide: 'contribute/docs_style_guide.md'
  - Writing code: 'contribute/writing_code.md'
  - Coding style guide: 'contribute/coding_style_guide.md'
  - Reporting bugs and requesting features: 'contribute/reporting_bugs.md'
  - Code of Conduct: 'contribute/code_of_conduct.md'
- FAQ: 'faq.md'


# Do not edit in PRs below here if you're a contributor

docs_dir: 'docs_dir'

site_name: Coral Project Docs

theme: 'mkdocs'

extra_css:
    - css/extra.css

markdown_extensions:
  - admonition
  - fenced_code
  - sane_lists
  - smarty


google_analytics: ['UA-73335347-3', 'docs.coralproject.net']



