# If you add a page, you must add it to the index here
pages:
- Home: 'index.md'
- Developer Guide:
  - Introduction: 'developer/index.md'
  - Architectural overview: 'developer/architectural_overview.md'
  - Installing Coral Ecosystem: 'quickstart/install.md'
  - Developer tools setup: 'developer/developer_setup.md'
  - Cay: 'cay/index.md'
  - Elkhorn: 'elkhorn/index.md'
  - Pillar: 'pillar/index.md'
  - Sponge: 'sponge/index.md'
  - Xenia: 'xenia/index.md'
  - Xenia Driver: 'xenia/xenia-driver-js.md'
- User Guide:
  - Introduction: 'user/index.md'
  - Trust: 'user/trust.md'
  - Ask: 'user/ask.md'
  - Talk: 'user/talk.md'
- Contribute:
  - Introduction: 'contribute/index.md'
  - Writing documentation: 'contribute/documentation/writing_documentation.md'
  - Documentation style guide: 'contribute/documentation/style_guide.md'
  - Reporting bugs and requesting features: 'contribute/reporting_bugs.md'
  - Writing code: 'contribute/development/writing_code.md'
  - Development workflow: 'contribute/development/working_with_github.md'
  - Coding style guide: 'contribute/development/style_guide.md'
  - Supporting the community: 'contribute/supporting_the_community.md'
  - Contributor License Agreement: 'contribute/contributor_license_agreement.md'
  - Coral naming: 'contribute/coral_naming.md'
- FAQ: 'faq.md'


# Do not edit in PRs below here
site_name: Coral Project Docs

markdown_extensions:
  - admonition
  - fenced_code
  - sane_lists
  - smarty

theme: mkdocs

docs_dir: 'docs_dir'
