mongodata:
   image: mongo:3.2.3
   ports:
       - "27017:27017"
   volumes:
       - /data/db
   command: mongod

rabbitmq:
  image: rabbitmq:management
  environment:
    - "RABBITMQ_DEFAULT_USER=${RABBIT_USER}"
    - "RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}"

pillarapp:
   image: coralproject/pillar
   environment:
           - "PILLAR_HOME=/opt/pillar"
           - "PILLAR_ADDRESS=:8080"
           - "MONGODB_URL=mongodb://mongodata:27017/coral"
           - "AMQP_URL=amqp://${RABBIT_USER}:${RABBIT_PASS}@rabbitmq:5672/"
   ports:
       - "8080:8080"
   links:
      - mongodata
      - rabbitmq

xeniaapp:
   image: coralproject/xenia
   environment:
           - "XENIA_MONGO_HOST=mongodata:27017"
           - "XENIA_AUTH=OFF"
           - "XENIA_MONGO_AUTHDB=coral"
           - "XENIA_MONGO_DB=coral"
           - "XENIA_MONGO_USER="
           - "XENIA_MONGO_PASS="
           - "XENIA_LOGGING_LEVEL=1"
           - "XENIA_HOST=:4000"
   ports:
       - "4000:4000"
   links:
      - mongodata

cayapp:
   image: coralproject/cay
   environment:
       - "XENIA_URL=${FRONTEND_HOST}:4000"
       - "PILLAR_URL=${FRONTEND_HOST}:8080"
       - "ENV=staging"
       - "PROJECT=Coral Project"
       - "GAID=${GAID_VALUE}"
       - "AUTH_TOKEN=${AUTH_TOKEN_VALUE}"
   ports:
       - "80:80"
   links:
       - pillarapp
       - xeniaapp
       - mongodata

sponge:
    image: coralproject/sponge
    environment:
        - "STRATEGY_CONF=/usr/local/strategy.json"
        - "PILLAR_URL=${FRONTEND_HOST}:8080"
